//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuoterPlan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172")]
        public int ImportDpi {
            get {
                return ((int)(this["ImportDpi"]));
            }
            set {
                this["ImportDpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172")]
        public int ImportManualDpi {
            get {
                return ((int)(this["ImportManualDpi"]));
            }
            set {
                this["ImportManualDpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AngleType {
            get {
                return ((int)(this["AngleType"]));
            }
            set {
                this["AngleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFFolder {
            get {
                return ((string)(this["PDFFolder"]));
            }
            set {
                this["PDFFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ThemeStyle {
            get {
                return ((int)(this["ThemeStyle"]));
            }
            set {
                this["ThemeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MruList {
            get {
                return ((string)(this["MruList"]));
            }
            set {
                this["MruList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SlopeType {
            get {
                return ((int)(this["SlopeType"]));
            }
            set {
                this["SlopeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImagesFolder {
            get {
                return ((string)(this["ImagesFolder"]));
            }
            set {
                this["ImagesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UICulture {
            get {
                return ((string)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fr")]
        public string InstallLanguage {
            get {
                return ((string)(this["InstallLanguage"]));
            }
            set {
                this["InstallLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ScrollSpeed {
            get {
                return ((int)(this["ScrollSpeed"]));
            }
            set {
                this["ScrollSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataFolder {
            get {
                return ((string)(this["DataFolder"]));
            }
            set {
                this["DataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bleu ciel")]
        public string ReportTheme {
            get {
                return ((string)(this["ReportTheme"]));
            }
            set {
                this["ReportTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExportToExcelType {
            get {
                return ((int)(this["ExportToExcelType"]));
            }
            set {
                this["ExportToExcelType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ortho {
            get {
                return ((bool)(this["Ortho"]));
            }
            set {
                this["Ortho"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrintPlanType {
            get {
                return ((int)(this["PrintPlanType"]));
            }
            set {
                this["PrintPlanType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConvertPDFToColor {
            get {
                return ((bool)(this["ConvertPDFToColor"]));
            }
            set {
                this["ConvertPDFToColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000000")]
        public double MaxPDFImportSize {
            get {
                return ((double)(this["MaxPDFImportSize"]));
            }
            set {
                this["MaxPDFImportSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<dotnetbarlayout version=\"6\" zorder=\"2,3,4,5\"> <docksite size=\"0\" dockingside=\"To" +
            "p\" originaldocksitesize=\"0\" /> <docksite size=\"0\" dockingside=\"Bottom\" originald" +
            "ocksitesize=\"0\" /> <docksite size=\"333\" dockingside=\"Left\" originaldocksitesize=" +
            "\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"> <barcontainer w=\"330\" h=\"189\"> " +
            "<bar name=\"containerBarNavigation\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=" +
            "\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockContainerItemPreview\" o" +
            "rigBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcontainer> <barcontainer " +
            "w=\"330\" h=\"350\"> <bar name=\"containerBarProperties\" dockline=\"0\" layout=\"2\" dock" +
            "offset=\"193\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockCont" +
            "ainerItemProperties\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcon" +
            "tainer> <barcontainer w=\"330\" h=\"109\"> <bar name=\"containerBarLayers\" dockline=\"" +
            "0\" layout=\"2\" dockoffset=\"527\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <i" +
            "tem name=\"dockContainerItemLayers\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> <" +
            "/bar> </barcontainer> </dockcontainer> </docksite> <docksite size=\"333\" dockings" +
            "ide=\"Right\" originaldocksitesize=\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"" +
            "> <barcontainer w=\"330\" h=\"423\"> <bar name=\"containerBarGroups\" dockline=\"0\" lay" +
            "out=\"2\" dockoffset=\"-1\" state=\"2\" dockside=\"2\" visible=\"true\"> <items> <item nam" +
            "e=\"dockContainerItemGroups\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> <" +
            "/barcontainer> <barcontainer w=\"330\" h=\"208\"> <bar name=\"containerBarRecentPlans" +
            "\" dockline=\"999\" layout=\"2\" dockoffset=\"427\" state=\"2\" dockside=\"2\" visible=\"tru" +
            "e\"> <items> <item name=\"dockContainerItemRecentPlans\" origBar=\"\" origPos=\"-1\" po" +
            "s=\"0\" /> </items> </bar> </barcontainer> </dockcontainer> </docksite> <bars> <ba" +
            "r name=\"containerBarEstimating\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=\"2\"" +
            " dockside=\"2\" visible=\"true\" autohide=\"true\" dockwidth=\"548\"> <items> <item name" +
            "=\"dockContainerItemEstimating\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar" +
            "> </bars> </dotnetbarlayout>")]
        public string TakeoffLayout {
            get {
                return ((string)(this["TakeoffLayout"]));
            }
            set {
                this["TakeoffLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<dotnetbarlayout version=\"6\" zorder=\"2,3,4,5\"> <docksite size=\"0\" dockingside=\"To" +
            "p\" originaldocksitesize=\"0\" /> <docksite size=\"0\" dockingside=\"Bottom\" originald" +
            "ocksitesize=\"0\" /> <docksite size=\"333\" dockingside=\"Left\" originaldocksitesize=" +
            "\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"> <barcontainer w=\"330\" h=\"189\"> " +
            "<bar name=\"containerBarNavigation\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=" +
            "\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockContainerItemPreview\" o" +
            "rigBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcontainer> <barcontainer " +
            "w=\"330\" h=\"350\"> <bar name=\"containerBarProperties\" dockline=\"0\" layout=\"2\" dock" +
            "offset=\"193\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockCont" +
            "ainerItemProperties\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcon" +
            "tainer> <barcontainer w=\"330\" h=\"109\"> <bar name=\"containerBarLayers\" dockline=\"" +
            "0\" layout=\"2\" dockoffset=\"527\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <i" +
            "tem name=\"dockContainerItemLayers\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> <" +
            "/bar> </barcontainer> </dockcontainer> </docksite> <docksite size=\"333\" dockings" +
            "ide=\"Right\" originaldocksitesize=\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"" +
            "> <barcontainer w=\"330\" h=\"423\"> <bar name=\"containerBarGroups\" dockline=\"0\" lay" +
            "out=\"2\" dockoffset=\"-1\" state=\"2\" dockside=\"2\" visible=\"true\"> <items> <item nam" +
            "e=\"dockContainerItemGroups\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> <" +
            "/barcontainer> <barcontainer w=\"330\" h=\"208\"> <bar name=\"containerBarRecentPlans" +
            "\" dockline=\"999\" layout=\"2\" dockoffset=\"427\" state=\"2\" dockside=\"2\" visible=\"tru" +
            "e\"> <items> <item name=\"dockContainerItemRecentPlans\" origBar=\"\" origPos=\"-1\" po" +
            "s=\"0\" /> </items> </bar> </barcontainer> </dockcontainer> </docksite> <bars> <ba" +
            "r name=\"containerBarEstimating\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=\"2\"" +
            " dockside=\"2\" visible=\"true\" autohide=\"true\" dockwidth=\"548\"> <items> <item name" +
            "=\"dockContainerItemEstimating\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar" +
            "> </bars> </dotnetbarlayout>")]
        public string EstimatingLayout {
            get {
                return ((string)(this["EstimatingLayout"]));
            }
            set {
                this["EstimatingLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Taxe 1")]
        public string Tax1Label {
            get {
                return ((string)(this["Tax1Label"]));
            }
            set {
                this["Tax1Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Taxe 2")]
        public string Tax2Label {
            get {
                return ((string)(this["Tax2Label"]));
            }
            set {
                this["Tax2Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tax1Rate {
            get {
                return ((double)(this["Tax1Rate"]));
            }
            set {
                this["Tax1Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Tax2Rate {
            get {
                return ((double)(this["Tax2Rate"]));
            }
            set {
                this["Tax2Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaxOnTax {
            get {
                return ((bool)(this["TaxOnTax"]));
            }
            set {
                this["TaxOnTax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<dotnetbarlayout version=\"6\" zorder=\"2,3,4,5\"> <docksite size=\"0\" dockingside=\"To" +
            "p\" originaldocksitesize=\"0\" /> <docksite size=\"0\" dockingside=\"Bottom\" originald" +
            "ocksitesize=\"0\" /> <docksite size=\"333\" dockingside=\"Left\" originaldocksitesize=" +
            "\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"> <barcontainer w=\"330\" h=\"189\"> " +
            "<bar name=\"containerBarNavigation\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=" +
            "\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockContainerItemPreview\" o" +
            "rigBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcontainer> <barcontainer " +
            "w=\"330\" h=\"350\"> <bar name=\"containerBarProperties\" dockline=\"0\" layout=\"2\" dock" +
            "offset=\"193\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <item name=\"dockCont" +
            "ainerItemProperties\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> </barcon" +
            "tainer> <barcontainer w=\"330\" h=\"109\"> <bar name=\"containerBarLayers\" dockline=\"" +
            "0\" layout=\"2\" dockoffset=\"527\" state=\"2\" dockside=\"1\" visible=\"true\"> <items> <i" +
            "tem name=\"dockContainerItemLayers\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> <" +
            "/bar> </barcontainer> </dockcontainer> </docksite> <docksite size=\"333\" dockings" +
            "ide=\"Right\" originaldocksitesize=\"0\"> <dockcontainer orientation=\"1\" w=\"0\" h=\"0\"" +
            "> <barcontainer w=\"330\" h=\"423\"> <bar name=\"containerBarGroups\" dockline=\"0\" lay" +
            "out=\"2\" dockoffset=\"-1\" state=\"2\" dockside=\"2\" visible=\"true\"> <items> <item nam" +
            "e=\"dockContainerItemGroups\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar> <" +
            "/barcontainer> <barcontainer w=\"330\" h=\"208\"> <bar name=\"containerBarRecentPlans" +
            "\" dockline=\"999\" layout=\"2\" dockoffset=\"427\" state=\"2\" dockside=\"2\" visible=\"tru" +
            "e\"> <items> <item name=\"dockContainerItemRecentPlans\" origBar=\"\" origPos=\"-1\" po" +
            "s=\"0\" /> </items> </bar> </barcontainer> </dockcontainer> </docksite> <bars> <ba" +
            "r name=\"containerBarEstimating\" dockline=\"0\" layout=\"2\" dockoffset=\"0\" state=\"2\"" +
            " dockside=\"2\" visible=\"true\" autohide=\"true\" dockwidth=\"548\"> <items> <item name" +
            "=\"dockContainerItemEstimating\" origBar=\"\" origPos=\"-1\" pos=\"0\" /> </items> </bar" +
            "> </bars> </dotnetbarlayout>")]
        public string DefaultLayout {
            get {
                return ((string)(this["DefaultLayout"]));
            }
            set {
                this["DefaultLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PrioSoft")]
        public string COfficePath {
            get {
                return ((string)(this["COfficePath"]));
            }
            set {
                this["COfficePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
            set {
                this["CompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyFullAddress {
            get {
                return ((string)(this["CompanyFullAddress"]));
            }
            set {
                this["CompanyFullAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CompanyRepresentative {
            get {
                return ((string)(this["CompanyRepresentative"]));
            }
            set {
                this["CompanyRepresentative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DefaultSystemType {
            get {
                return ((int)(this["DefaultSystemType"]));
            }
            set {
                this["DefaultSystemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DefaultPrecision {
            get {
                return ((int)(this["DefaultPrecision"]));
            }
            set {
                this["DefaultPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSaved {
            get {
                return ((string)(this["LastSaved"]));
            }
            set {
                this["LastSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FiltersWindowPosition {
            get {
                return ((global::System.Drawing.Point)(this["FiltersWindowPosition"]));
            }
            set {
                this["FiltersWindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size FiltersWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["FiltersWindowSize"]));
            }
            set {
                this["FiltersWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImportDBPricesSkuPosition {
            get {
                return ((int)(this["ImportDBPricesSkuPosition"]));
            }
            set {
                this["ImportDBPricesSkuPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ImportDBPricesPricePosition {
            get {
                return ((int)(this["ImportDBPricesPricePosition"]));
            }
            set {
                this["ImportDBPricesPricePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportDBPricesFileName {
            get {
                return ((string)(this["ImportDBPricesFileName"]));
            }
            set {
                this["ImportDBPricesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BackupInterval {
            get {
                return ((int)(this["BackupInterval"]));
            }
            set {
                this["BackupInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DBIsReadOnly {
            get {
                return ((bool)(this["DBIsReadOnly"]));
            }
            set {
                this["DBIsReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableAutoBackup {
            get {
                return ((bool)(this["EnableAutoBackup"]));
            }
            set {
                this["EnableAutoBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowMultipleInstances {
            get {
                return ((bool)(this["AllowMultipleInstances"]));
            }
            set {
                this["AllowMultipleInstances"] = value;
            }
        }
    }
}
